INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (1,'El','1 do promienia światła +50 do skuteczności ataku','1 do promienia światła +15 do obrony ','1 do promienia światła +15 do obrony',11);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (2,'Eld','50 do skuteczności ataku przeciwko nieumarłym +75% do obrażeń przeciwko nieumarłym','-15% spalanie wytrzymałości ','+7% zwiększona szansa na blok',11);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (3,'Tir','+2 many za zabicie potwora','+2 many za zabicie potwora ','+2 many za zabicie potwora',13);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (4,'Nef','Odrzucenie','+30 do obrony przeciwko pociskom ','+30 do obrony przeciwko pociskom',13);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (5,'Eth','-25% do Obrony potworów na uderzenie','+15% do odzyskiwania many ','+15% do odzyskiwania many',15);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (6,'Ith','+9 do maksymalnych obrażeń','15% obrażeń przechodzi na manę ','15% obrażeń przechodzi na manę',15);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (7,'Tal','+75 obrażeń od trucizny przez 1 sekundę','+30% do odporności na trucizny ','+35% do odporności na trucizny',17);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (8,'Ral','+5-30 obrażeń od ognia','+30% do odporności na ogień ','+35% do odporności na ogień',19);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (9,'Ort','+1-50 obrażeń od błyskawic','+30% do odporności na błyskawice ','+35% do odporności na błyskawice',21);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (10,'Thul','+3-14 obrażeń od zimna','+30% do odporności na zimno ','+35% do odporności na zimno',23);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (11,'Amn','7% wyssanie życia','Atakujący otrzymuje obrażenia 14 ','Atakujący otrzymuje obrażenia 14',25);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (12,'Sol','+9 do minimalnych obrażeń','obrażenia zmniejszone o 7 ','obrażenia zmniejszone o 7',27);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (13,'Shael','Zwiększona Szybkość Ataku (20%)','Szybsze odzyskiwanie równowagi (20%) ','Szybsze Blokowanie o 20%',29);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (14,'Dol','25% szansa na ucieczkę wroga po trafieniu','Odzyskiwanie życia +7 ','Odzyskiwanie życia +7',31);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (15,'Hel','wymagania -20%','wymagania -15% ','wymagania -15%',1);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (16,'Io','+10 do żywotności','+10 do żywotności ','+10 do żywotności',35);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (17,'Lum','+10 do energii','+10 do energii ','+10 do energii',37);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (18,'Ko','+10 do zręczności','+10 do zręczności ','+10 do zręczności',39);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (19,'Fal','+10 do siły','+10 do siły ','+10 do siły',41);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (20,'Lem','+75% więcej złota od potworów','+50% więcej złota od potworów ','+50% więcej złota od potworów',43);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (21,'Pul','100 do skuteczności ataku przeciwko demonom , +75% do obrażeń przeciwko demonom','+30% do obrony ','+30% do obrony',45);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (23,'Um','25% szansy na otwarcie rany','+15% do wszystkich odporności ','+22% do wszystkich odporności',47);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (23,'Mal','Uniemożliwia leczenie się potworów','Obrażenia od magii zmniejszone o 7 ','Obrażenia od magii zmniejszone o 7',49);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (24,'Ist','30% większa szansa na znalezienie magicznych przedmiotów','25% większa szansa na znalezienie magicznych przedmiotów ','25% większa szansa na znalezienie magicznych przedmiotów',51);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (25,'Gul','+20% do skuteczności ataku','+5% do maksymalnej odporności na trucizny ','+5% do maksymalnej odporności na trucizny',53);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (26,'Vex','Wykrada 7% many','+5% do maksymalnej odporności na ogień ','+5% do masymalnej odporności na ogień',55);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (27,'Ohm','+50% do obrażeń','+5% do masymalnej odporności na zimno ','+5% do masymalnej odporności na zimno',57);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (28,'Lo','20% szansy na zadanie Śmiertelnego Ciosu','+5% do masymalnej odporności na błyskawice ','+5% do masymalnej odporności na błyskawice',59);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (29,'Sur','20% szansy na to, że trafienie oślepi cel','+5% do many ','+50 do many',61);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (30,'Ber','20% szansy na Druzgocące Uderzenie','Obrażenia zmniejszone o 8% ','Obrażenia zmniejszone o 8%',63);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (31,'Jah','Ignoruje obronę celu','+5% do życia ','+50 do życia',65);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (32,'Cham','Zamraża cel +3','Nie można zamrozić ','Nie można zamrozić',67);
INSERT INTO rune(id, name, weaponBuff, shieldBuff, armourBuff, price) VALUES (33,'Zod','Niezniszczalne','Niezniszczalne ','Niezniszczalne',69);
